# fly.toml app configuration file generated for spot-tops-server on 2023-12-24T15:52:51-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spot-tops-server"
primary_region = "ord"

[build]
  dockerfile = "dockerfile"
  # image = "danydodson/spot-tops-server:latest"

[env]
  REDIRECT_URI = "http://localhost:8888/callback"
  FRONTEND_URI = "http://localhost:8888"
  LOGIN_URI = "http://localhost:8888/login"

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
