app = "spot-tops-server"
primary_region = "ord"

[build]
  dockerfile = "dockerfile"
  # image = "danydodson/spot-tops-server:latest"

[env]
  REDIRECT_URI = "https://spot-tops.com/callback"
  FRONTEND_URI = "https://spot-tops.com"
  LOGIN_URI = "https://spot-tops.com/login"

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
